server:
  port: 9090
  error:
    path: /error

spring:
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        soccer-channel:
          destination: soccer
        hockey-channel:
          destination: hockey
        basketball-channel:
          destination: basketball
        news-channel:
          destination: news
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

scorecard:
  sports-configured: soccer hockey
  news-enabled: true
  event:
    handler:
      soccer:
        aliveTime: 5000
        mininimumSleepInterval: 4000
        maximumSleepInterval: 11000
      hockey:
        aliveTime: 5000
        mininimumSleepInterval: 4000
        maximumSleepInterval: 11000
      basketball:
        aliveTime: 5000
        mininimumSleepInterval: 4000
        maximumSleepInterval: 11000